# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Recipe.create(name: 'Bloody Mary', description: "2 part tomato juice, 1 part vodka", image:"http://liquor.s3.amazonaws.com/wp-content/uploads/2012/01/classic-bloody-mary.jpg")
Recipe.create(name: 'Rum and Coke', description: "2 part coke, 1 part rum", image:"http://talltalesfromkansas.typepad.com/.a/6a01538dee917a970b01a511949884970c-pi")
Recipe.create(name: 'Alabama Slammer', description: "2 part Bourbon, 2 part liqueur, 1 part Orange Juice, 1 part Sour Mix", image:"http://www.allaboutbarsinfo.com/wp-content/uploads/2011/02/3-fancy-drinks.jpg")
Recipe.create(name: 'Blue Hawaiian', description: "2 part Pineapple Juice, 1 part Liqueur, 1 part Rum", image:"http://pad1.whstatic.com/images/thumb/9/97/Make-a-Blue-Hawaii-Step-5.jpg/530px-Make-a-Blue-Hawaii-Step-5.jpg")
Recipe.create(name: 'Tequila Sunrise', description: "2 part Tequila, 1 part Orange Juice, splash of Grenadine", image:"http://pre05.deviantart.net/cb0d/th/pre/i/2012/310/1/d/tequila_sunrise_by_past1978-d2vfofz.jpg")
Recipe.create(name: 'Martini Cocktail', description: "3 part Gin, 1 part Vermouth", image:"http://www.thelifeofluxury.com/images/martini_cocktail.jpg")
Recipe.create(name: 'Whiskey Sour', description: "2 part Scotch, 1 part Sour Mix, 1 part Simple Syrup", image:"http://liquor.s3.amazonaws.com/wp-content/uploads/2011/07/fa-Whiskey-Sour.jpg")

Ingredient.create(name: 'Vodka', alcoholic: true)
Ingredient.create(name: 'Rum', alcoholic: true)
Ingredient.create(name: 'Tequila', alcoholic: true)
Ingredient.create(name: 'Gin', alcoholic: true)
Ingredient.create(name: 'Liqueur', alcoholic: true)
Ingredient.create(name: 'Bourbon', alcoholic: true)
Ingredient.create(name: 'Scotch', alcoholic: true)
Ingredient.create(name: 'Irish Whiskey', alcoholic: true)
Ingredient.create(name: 'Canadian Whiskey', alcoholic: true)

Ingredient.create(name: 'Coke', alcoholic: false)
Ingredient.create(name: 'Diet Coke', alcoholic: false)
Ingredient.create(name: 'Sprite', alcoholic: false)
Ingredient.create(name: 'Ginger Ale', alcoholic: false)
Ingredient.create(name: 'Club Soda', alcoholic: false)
Ingredient.create(name: 'Tonic', alcoholic: false)
Ingredient.create(name: 'Orange Juice', alcoholic: false)
Ingredient.create(name: 'Pineapple Juice', alcoholic: false)
Ingredient.create(name: 'Cranberry Juice', alcoholic: false)
Ingredient.create(name: 'Triple Sec', alcoholic: false)
Ingredient.create(name: 'Simple Syrup', alcoholic: false)
Ingredient.create(name: 'Tomato Juice', alcoholic: false)
Ingredient.create(name: 'Grenadine', alcoholic: false)
Ingredient.create(name: 'Sour Mix', alcoholic: false)
Ingredient.create(name: 'Lemonade', alcoholic: false)
Ingredient.create(name: 'Vermouth', alcoholic: false)

RecipeIngredient.create(recipe_id: 1, ingredient_id: 1)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 21)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 2)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 10)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 5)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 6)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 16)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 23)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 2)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 5)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 17)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 3)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 16)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 22)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 4)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 25)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 7)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 20)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 23)



